/* Vista de permisos desde el punto de vista del cliente / portal. */
(()=>{
  const clients=[
    {name:'Grupo Battaglia',contact:'María Battaglia · Directora',entities:[['Alto Paraná S.A.','IVA, Societario y documentos habilitados'],['Battaglia Servicios S.R.L.','Documentos y vencimientos habilitados']],enabled:[['Documentos','DDJJ, acuses y archivos que el Estudio publique','▣'],['DDJJ y vencimientos','Obligaciones habilitadas y sus fechas relevantes','◷'],['Mensajes con Dahlgren','Solicitudes y comunicaciones asociadas al Grupo','✦'],['Estado de cuenta','Resumen comercial habilitado por el Estudio','◫']],hidden:['Información de otros Grupos o Entidades','Papeles de trabajo, notas internas y borradores','Permisos, auditoría y trazabilidad interna','Honorarios internos, costos y márgenes del Estudio']},
    {name:'Grupo Litoral',contact:'Juan Litoral · Administrador',entities:[['Grupo Litoral S.A.','IVA, IIBB e informes mensuales']],enabled:[['Documentos','DDJJ y acuses publicados','▣'],['DDJJ y vencimientos','Calendario de obligaciones habilitadas','◷'],['Mensajes con Dahlgren','Canal de solicitudes y novedades','✦'],['Informes','Informes ejecutivos aprobados','▤']],hidden:['Información de otras entidades','Datos de colaboradores del Estudio','Borradores, observaciones y trabajo interno','Cuenta corriente interna y métricas globales']}
  ];
  let selected=0;
  const accessPage=()=>{const c=clients[selected];return `${header('Administración / Portal','Accesos por cliente','Definí qué información queda habilitada para cada Grupo y contacto del portal.',`<button class="outline" data-roles-return>← Roles y permisos</button>`)}<section class="card client-access-top"><div><div class="eyebrow">CLIENTE / GRUPO SELECCIONADO</div><h2>${c.name}</h2><p>${c.contact} · Acceso de portal activo</p></div><label><span class="eyebrow">CAMBIAR CLIENTE</span><select data-client-access>${clients.map((x,i)=>`<option value="${i}" ${i===selected?'selected':''}>${x.name}</option>`).join('')}</select></label></section><section class="client-access-grid"><article class="card"><div class="eyebrow">PORTAL HABILITADO</div><h3 class="section-title">Qué puede consultar este cliente</h3>${c.enabled.map(x=>`<div class="portal-permission"><span class="portal-permission-icon">${x[2]}</span><span><b>${x[0]}</b><small>${x[1]}</small></span><em class="permission-on">HABILITADO</em></div>`).join('')}<div class="doc-actions"><button class="outline" data-client-toast="Edición de módulos del portal simulada">Editar módulos</button><button class="primary" data-client-toast="Cambios de acceso del cliente guardados como demostración">Guardar accesos</button></div></article><aside class="card"><div class="eyebrow">ENTIDADES HABILITADAS</div><h3 class="section-title">Alcance del Grupo</h3>${c.entities.map(x=>`<div class="client-entity-row"><span><b>${x[0]}</b><small>${x[1]}</small></span><em class="permission-on">PORTAL</em></div>`).join('')}<div class="eyebrow" style="margin-top:20px">NO VISIBLE PARA EL CLIENTE</div><ul class="restriction-list">${c.hidden.map(x=>`<li>${x}</li>`).join('')}</ul></aside></section><section class="client-access-rule"><b>Regla de publicación:</b> el cliente sólo ve información asociada a sus Entidades y marcada explícitamente como publicable. La existencia de un documento o dato interno no implica que esté disponible en el portal.</section><p class="demo-note">Configuración demostrativa. En la versión real, cada cambio debería conservar responsable, fecha, alcance y registro de auditoría.</p>`};
  const pageBeforeClientAccess=page;
  page=function(){if(state.page==='accesos-cliente')return accessPage();return pageBeforeClientAccess()};
  const entries=()=>{if(state.page==='integraciones'){const head=document.querySelector('.page-head');if(head&&!head.querySelector('[data-client-access-open]')){const button=document.createElement('button');button.className='outline client-access-entry';button.dataset.clientAccessOpen='';button.textContent='Accesos de clientes';head.append(button)}}if(state.page==='permisos'){const head=document.querySelector('.page-head');if(head&&!head.querySelector('[data-client-access-open]')){const button=document.createElement('button');button.className='outline client-access-entry';button.dataset.clientAccessOpen='';button.textContent='Accesos de clientes';head.append(button)}}};
  document.addEventListener('click',event=>{if(event.target.closest('[data-client-access-open]')){event.preventDefault();state.page='accesos-cliente';location.hash='accesos-cliente';app()}if(event.target.closest('[data-roles-return]')){event.preventDefault();state.page='permisos';location.hash='permisos';app()}const toastButton=event.target.closest('[data-client-toast]');if(toastButton){event.preventDefault();toast(toastButton.dataset.clientToast)}});
  const originalApp=app;
  app=function(){originalApp();entries();document.querySelector('[data-client-access]')?.addEventListener('change',event=>{selected=Number(event.target.value);app()})};
  if(state.page!=='login')app();
})();
