/* Evolución funcional: capa de navegación para la presentación a socios.
   Conserva las vistas de detalle existentes y redefine sólo los recorridos principales. */
(() => {
  const demoNote = '<p class="demo-note">Datos de ejemplo · Integración prevista, aún no sincronizada.</p>';
  const groups = [
    { name:'Grupo Battaglia', entities:['Alto Paraná S.A.','María Battaglia','Tomás Battaglia'], lead:'Lucía Fernández', due:'IVA · agosto 2026', state:'Requiere atención', balance:'$ 1.240.000' },
    { name:'Grupo Litoral', entities:['Grupo Litoral S.A.','Litoral Inversiones S.A.'], lead:'Martín Acosta', due:'Anticipo de Ganancias', state:'Al día', balance:'$ 684.000' },
    { name:'Grupo François', entities:['COMDETUR S.A.','Humberto François','Yanick François'], lead:'Sofía Ríos', due:'Renovación de autoridades', state:'Próximo', balance:'$ 328.000' }
  ];
  const go = route => { state.page=route; history.pushState(null,'',`#${route}`); app(); };
  const head = (eyebrow,title,text,action='') => `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${text}</p></div>${action}</div>`;
  const badge = text => `<span class="evo-badge ${text==='Requiere atención'?'danger':text==='Próximo'?'warn':''}">${text}</span>`;
  const agent = (context='Estudio') => `<section class="dahlgren-agent"><div class="agent-orb">✦</div><div><div class="eyebrow">AGENTE DAHLGREN · ${context.toUpperCase()}</div><h3>¿Qué necesitás resolver?</h3><p>Asistente demostrativo con respuestas contextualizadas y permisos por perfil.</p></div><div class="agent-query"><input placeholder="${context==='Dirección'?'¿Cómo vienen las cobranzas respecto del mes anterior?':context==='Cliente'?'Mostrame mis últimas DDJJ.':'¿Qué vence esta semana para Alto Paraná S.A.?'}"><button class="primary" data-evo-toast="Respuesta simulada del Agente Dahlgren preparada">Consultar</button></div></section>`;
  documents=function(){let items=[['PDF','DDJJ IVA · agosto 2026','Alto Paraná S.A. · Impositivo','Obligación: IVA · Período: agosto 2026',['Estado: en revisión','Responsable: Lucía Fernández']],['PDF','Acta de directorio','Alto Paraná S.A. · Societario','Autoridades · Mandato con vencimiento 30/09/2026',['Datos: autoridades','Fuente: OneDrive']],['XLS','Papel de trabajo IVA','Alto Paraná S.A. · Impositivo','Obligación: IVA · Período: agosto 2026',['Conciliación','Fuente: OneDrive']]];return `${head('Documentos','Documentos con contexto','Del archivo original a información relacionada, verificable y útil para trabajar.',`<div class="header-actions"><button class="outline" data-onedrive-sync>Sincronizar OneDrive</button><button class="primary" data-modal="document">Subir documento</button></div>`)}<section class="document-origin"><div><span class="document-origin-icon">◫</span><span><b>OneDrive · origen documental previsto</b><small>Los archivos originales permanecen en Microsoft OneDrive; Dahlgren organiza su contexto y metadatos.</small></span></div><em>Conexión demostrativa · no sincronizada</em></section><section class="document-journey"><article><span>01 · ARCHIVO ORIGINAL</span><b>Recibir o detectar documento</b><small>Subido por un usuario o incorporado desde OneDrive.</small></article><article><span>02 · CONTEXTO</span><b>Asociar al expediente</b><small>Grupo, Entidad, área, obligación y período.</small></article><article><span>03 · INFORMACIÓN</span><b>Extraer, revisar y relacionar</b><small>Datos estructurados con fuente original y trazabilidad.</small></article></section><section class="document-context-grid"><article class="card"><div class="eyebrow">EJEMPLOS EN CONTEXTO</div><h3 class="section-title">Los documentos dejan de estar aislados</h3><div class="document-context-list">${items.map(([type,name,context,relation,tags])=>`<article class="document-context-card"><span class="document-type">${type}</span><div><b>${name}</b><small>${context}</small><div class="document-context-meta"><span>${relation}</span>${tags.map(x=>`<span>${x}</span>`).join('')}</div></div><button data-evo-toast="Vista demostrativa del original en OneDrive preparada">Ver original ↗</button></article>`).join('')}</div></article><aside class="card document-review"><div class="eyebrow">REVISIÓN HUMANA</div><h3>Casos que requieren criterio</h3><div class="document-review-item"><b>Balance 2025 · Norte Agroindustrial</b><small>Dos observaciones antes de asociar datos contables estructurados.</small></div><div class="document-review-item"><b>Factura A 0004-003829</b><small>Posible duplicado; se conserva el original y se solicita confirmación.</small></div><button class="outline" data-go="tareas">Ver atención requerida</button></aside></section>${demoNote}`};
  const documentsWithContext=documents;
  documents=function(){return `${documentsWithContext()}<section class="document-scope"><article class="card"><div class="eyebrow">MAPA DE ASOCIACIÓN</div><h3 class="section-title">Un expediente documental completo</h3><div class="document-path"><span>Grupo Battaglia</span><i>→</i><span>Alto Paraná S.A.</span><i>→</i><span>Impositivo</span><i>→</i><span>IVA</span><i>→</i><span>Agosto 2026</span></div><div class="document-evidence"><span><b>DDJJ</b><small>Declaración presentada</small></span><span><b>Acuse</b><small>Evidencia de presentación</small></span><span><b>Papeles de trabajo</b><small>Soporte y conciliación</small></span></div><div class="document-rule-list"><div><span>1</span><p>El original conserva su referencia a OneDrive, versión, fecha y responsable.</p></div><div><span>2</span><p>Dahlgren guarda metadatos, contexto y relaciones; no replica el árbol de carpetas.</p></div><div><span>3</span><p>Los datos extraídos quedan identificados con su documento fuente y estado de revisión.</p></div></div></article><article class="card"><div class="eyebrow">INVENTARIO INICIAL A RELEVAR</div><h3 class="section-title">Familias documentales previstas</h3><div class="document-inventory"><div><b>Societario</b><small>Actas, estatutos, poderes, contratos, libros y autoridades.</small></div><div><b>Impositivo</b><small>DDJJ, acuses, compensaciones y papeles de trabajo.</small></div><div><b>Contable</b><small>Balances, Excel contables, cierres e informes.</small></div><div><b>Laboral</b><small>Legajos, recibos, novedades y documentación autorizada.</small></div><div><b>Jurídico</b><small>Contratos, expedientes, informes y pruebas.</small></div><div><b>Administrativo</b><small>Comprobantes, pagos y documentación de cobranzas.</small></div></div><p class="document-scope-note">Categorías demostrativas basadas en el relevamiento funcional. El inventario real se completa al analizar el repositorio del Estudio.</p></article></section>${demoNote}`};
  function study(){ return `${head('Estudio · Dirección','Situación del Estudio','Indicadores gerenciales para decidir.')} ${agent('Dirección')}<div class="evo-kpis"><article><small>DISPONIBILIDADES</small><b>$ 42,8 M</b><span>Caja y bancos</span></article><article><small>COBRANZAS</small><b>$ 8,6 M</b><span>Acumulado septiembre</span></article><article><small>HONORARIOS</small><b>$ 21,8 M</b><span>Mensuales · +12,1%</span></article><article><small>CUENTAS POR COBRAR</small><b>$ 6,3 M</b><span>18% vencido</span></article></div><section class="evo-two"><article class="card"><div class="eyebrow">ATENCIÓN DE DIRECCIÓN</div><h3>Decisiones que requieren intervención</h3><button class="evo-row" data-go="grupos"><b>Grupo Battaglia</b><span>Saldo vencido y DDJJ IVA próxima</span><em>Ver grupo →</em></button><button class="evo-row" data-go="grupos"><b>Grupo François</b><span>Mandato de autoridades vence en 20 días</span><em>Asignar seguimiento →</em></button><button class="evo-row" data-go="tareas"><b>4 cobranzas</b><span>Imputación pendiente de revisión</span><em>Revisar →</em></button></article><article class="card"><div class="eyebrow">RESULTADO</div><h3>Ingresos, gastos y evolución</h3><div class="evo-result"><b>$ 4,7 M</b><span>Resultado acumulado del mes</span></div><p class="muted">Los datos administrativos se conectarán desde SARF luego del relevamiento técnico. Esta pantalla no representa una sincronización activa.</p></article></section>${demoNote}`; }
  function groupsPage(){ return `${head('Clientes','Grupos Cliente','La relación comercial se organiza por Grupo; cada Grupo reúne sus Entidades.', '<button class="outline" data-evo-toast="Alta de Grupo disponible en la etapa operativa">+ Nuevo grupo</button>')}<section class="group-path">Grupo Cliente <i>→</i> Entidades <i>→</i> Área <i>→</i> Obligación o proceso <i>→</i> Período <i>→</i> Información y documentos</section><div class="group-list">${groups.map((g,i)=>`<button class="group-card" data-go="grupo/${i}"><div class="group-icon">${g.name.split(' ')[1][0]}</div><div><div class="eyebrow">GRUPO CLIENTE</div><h3>${g.name}</h3><p>${g.entities.length} entidades · Responsable: ${g.lead}</p></div><div class="group-status">${badge(g.state)}<small>${g.due}</small></div><em>→</em></button>`).join('')}</div>${demoNote}`; }
  function groupDetail(n=0){ let g=groups[n]; return `${head('Clientes / Grupo Cliente',g.name,'Resumen consolidado, Entidades, asuntos y responsables.', '<button class="outline" data-go="grupos">← Todos los grupos</button>')} ${agent('Profesional')}<section class="group-summary"><div><small>RESPONSABLE INTERNO</small><b>${g.lead}</b></div><div><small>PRÓXIMO VENCIMIENTO</small><b>${g.due}</b></div><div class="internal-only"><small>SALDO HONORARIOS · INTERNO</small><b>${g.balance}</b></div></section><div class="evo-two"><article class="card"><div class="eyebrow">ENTIDADES DEL GRUPO</div><h3>Seleccioná una Entidad para ver su contexto 360°</h3>${g.entities.map((x,i)=>`<button class="entity-row" data-go="entidad/${n}/${i}"><span>${i===0?'SA':'PH'}</span><b>${x}</b><small>${i===0?'Sociedad anónima · Impositivo, Contable, Societario':'Persona humana · Impositivo y Patrimonial'}</small><em>→</em></button>`).join('')}</article><article class="card"><div class="eyebrow">ASUNTOS PENDIENTES</div><h3>Seguimiento del Grupo</h3><p><b>IVA agosto</b><br><small>Alto Paraná S.A. · vence 18/09 · responsable: Lucía Fernández</small></p><p><b>Comunicación ARCA detectada</b><br><small>Requiere revisión antes de cualquier apertura explícita.</small></p><button class="outline" data-go="tareas">Ver tareas y seguimiento</button></article></div>${demoNote}`; }
  function entity(n=0,e=0){let g=groups[n], name=g.entities[e]; return `${head('Grupo Cliente / Entidad',name,'Una vista única para información, obligaciones, documentos y acciones.', '<button class="outline" data-go="grupo/'+n+'">← Volver al Grupo</button>')}<section class="entity-hero"><div><div class="eyebrow">ENTIDAD 360°</div><h2>${name}</h2><p>CUIT 30-71452689-1 · Sociedad anónima · Responsable: Lucía Fernández</p></div><div class="entity-rel"><small>RELACIONES</small><b>María Battaglia</b><span>Directora · Socia</span><b>Tomás Battaglia</b><span>Apoderado</span></div></section>${agent('Profesional')}<div class="entity-grid"><article class="card"><div class="eyebrow">ÁREAS ATENDIDAS</div><h3>Trabajo profesional</h3><button class="area-link" data-go="obligacion"><b>Impositivo</b><span>IVA · Agosto 2026</span><em>Ver obligación →</em></button><button class="area-link"><b>Societario</b><span>Autoridades y mandatos</span><em>Ver documentos →</em></button><button class="area-link"><b>Contable</b><span>Cierre agosto · En revisión</span><em>Ver detalle →</em></button></article><article class="card"><div class="eyebrow">NOVEDADES Y OBLIGACIONES</div><h3>Requiere seguimiento</h3><button class="notice detected" data-go="novedad"><b>Comunicación detectada</b><span>Domicilio Fiscal Electrónico</span><small>Aún no abierta · revisión requerida</small></button><button class="notice"><b>Vencimiento próximo</b><span>IVA · 18/09/2026</span><small>Documentación completa · revisión pendiente</small></button><button class="notice"><b>DDJJ presentada</b><span>Ingresos Brutos · julio</span><small>Acuse asociado</small></button></article><article class="card"><div class="eyebrow">ACTIVIDAD RECIENTE</div><h3>Historial breve</h3><p>Hoy · Se incorporó papel de trabajo de IVA.</p><p>Ayer · Lucía solicitó revisión del borrador.</p><p>03 sep · DDJJ de IIBB presentada con acuse.</p></article></div>${demoNote}`; }
  function obligation(){return `${head('Entidad / Impositivo / IVA','IVA · Agosto 2026','El documento deja de estar aislado: se vincula a una obligación y período.','<button class="outline" data-go="entidad/0/0">← Entidad 360°</button>')}<section class="obligation-head"><span>ESTADO<br><b>En revisión</b></span><span>VENCIMIENTO<br><b>18/09/2026</b></span><span>RESPONSABLE<br><b>Lucía Fernández</b></span></section><article class="card"><div class="eyebrow">EVIDENCIA DEL PERÍODO</div><h3>Información y documentos asociados</h3><div class="doc-context"><b>DDJJ IVA agosto 2026</b><span>Declaración jurada · preparada</span><button data-evo-toast="Vista demostrativa del original en OneDrive">Ver original en OneDrive ↗</button></div><div class="doc-context"><b>Acuse de presentación</b><span>Disponible luego de la presentación</span><button data-evo-toast="Acuse de ejemplo">Ver acuse</button></div><div class="doc-context"><b>Papeles de trabajo</b><span>Excel · actualizado hoy</span><button data-evo-toast="Papel de trabajo de ejemplo">Ver documento</button></div></article>${demoNote}`}
  function tasks(){return `${head('Atención / Tareas','Seguimiento y decisiones','Excepciones asignadas con contexto, responsable y trazabilidad.')}<article class="card"><div class="task-flow">Novedad <i>→</i> Entidad <i>→</i> Área <i>→</i> Responsable <i>→</i> Tarea <i>→</i> Seguimiento</div><button class="task-item" data-go="novedad"><b>Nueva comunicación ARCA</b><span>Alto Paraná S.A. · Impositivo · Lucía Fernández</span><small>Revisión necesaria antes de abrir la notificación</small><em>Ver →</em></button><button class="task-item"><b>Imputar cobranza</b><span>Grupo Battaglia · Administración · Martín Acosta</span><small>Vence hoy · propuesta de imputación disponible</small><em>Asignar →</em></button></article>${demoNote}`}
  function notice(){return `${head('Novedades y obligaciones','Comunicación detectada','Alto Paraná S.A. · Domicilio Fiscal Electrónico','<button class="outline" data-go="tareas">← Tareas</button>')}<section class="notice-detail"><span class="detected-label">DETECTADA · NO ABIERTA</span><h2>Nueva comunicación de ARCA</h2><p>La lectura de una notificación puede producir efectos legales. En el producto real debe ser una acción explícita, autorizada y auditada.</p><div><b>Responsable propuesto:</b> Lucía Fernández · Impositivo</div><button class="primary" data-evo-toast="Tarea simulada creada y asignada a Lucía Fernández">Crear y asignar tarea</button><button class="outline" data-evo-toast="Acción de apertura disponible sólo con autorización">Abrir notificación (demo)</button></section>${demoNote}`}
  function portal(){return `${head('Portal Cliente','Grupo Battaglia','Información habilitada para tus Entidades.')} ${agent('Cliente')}<div class="evo-kpis portal-kpis"><article><small>PRÓXIMO VENCIMIENTO</small><b>18 SEP</b><span>IVA · Alto Paraná S.A.</span></article><article><small>DOCUMENTOS RECIENTES</small><b>4</b><span>DDJJ y acuses disponibles</span></article><article><small>ESTADO DE CUENTA</small><b>$ 1,24 M</b><span>Saldo pendiente</span></article></div><div class="evo-two"><article class="card"><div class="eyebrow">MIS ENTIDADES</div><h3>Alto Paraná S.A.</h3><p>IVA agosto en revisión · Vence 18/09</p><button class="outline" data-go="obligacion">Consultar DDJJ</button></article><article class="card"><div class="eyebrow">SOLICITUDES</div><h3>Comunicación con Dahlgren</h3><p>Tenés una solicitud de documentación pendiente.</p><button class="outline" data-evo-toast="Mensaje demostrativo para Dahlgren preparado">Enviar mensaje</button></article></div>${demoNote}`}
  const originalPage=page;
  page=function(){ if(state.profile==='Cliente' && !['login','obligacion'].includes(state.page)) return portal(); if(state.page==='inicio') return study(); if(state.page==='clientes'||state.page==='grupos') return groupsPage(); if(state.page.startsWith('grupo/')) return groupDetail(+state.page.split('/')[1]); if(state.page.startsWith('entidad/')) {let x=state.page.split('/');return entity(+x[1],+x[2]);} if(state.page==='obligacion')return obligation(); if(state.page==='tareas')return tasks(); if(state.page==='novedad')return notice(); return originalPage(); };
  const originalShell=shell;
  shell=function(){
    let html=originalShell(), internal=state.profile!=='Cliente';
    let allAreas=[['impositivo','Fiscal'],['previsional','Laboral'],['contabilidad','Contable'],['societario','Societario'],['contencioso','Jurídico'],['financiero','Financiero'],['documental','Documental'],['auditoria','Auditoría'],['atencion','Atención']];
    let permitted=state.profile==='Socio / Administrador'?allAreas:state.profile==='Asesor Financiero'?allAreas.filter(x=>['financiero','contabilidad','auditoria','documental'].includes(x[0])):allAreas.filter(x=>['impositivo','previsional','contabilidad','societario','documental','atencion'].includes(x[0]));
    let areaButtons=permitted.map(([id,label])=>`<button data-go="areas/${id}" class="${state.page.startsWith('areas/'+id)?'active':''}"><span>◦</span>${label}</button>`).join('');
    let nav=internal?`<div class="evo-nav"><span>ESTUDIO</span><button data-go="inicio" class="${state.page==='inicio'?'active':''}">Dirección</button><span>CLIENTES</span><button data-go="grupos" class="${state.page==='grupos'||state.page==='clientes'||state.page.startsWith('grupo/')||state.page.startsWith('entidad/')?'active':''}">Grupos y Entidades</button><button data-go="tareas" class="${state.page==='tareas'?'active':''}">Atención / Tareas</button><button data-go="documentos" class="${state.page==='documentos'?'active':''}">Documentos</button><details class="evo-area-menu" ${state.page.startsWith('areas/')?'open':''}><summary>ÁREAS DE TRABAJO <i>⌄</i></summary>${areaButtons}</details><span>GESTIÓN</span><button data-go="areas/administracion" class="${state.page==='areas/administracion'?'active':''}">Administración</button></div>`:`<div class="evo-nav evo-client-nav"><span>MI PORTAL</span><button data-go="inicio">Inicio</button><button data-go="obligacion">DDJJ y documentos</button><button data-go="comunicaciones">Mensajes con Dahlgren</button></div>`;
    html=html.replace(/<nav class="nav[\s\S]*?<\/nav>/,`<nav class="nav grouped-nav">${nav}</nav>`);
    html=html.replace(/<button class="assist-entry[\s\S]*?<\/button>/,'<button class="assist-entry evo-assist" data-evo-agent><span>✦</span><b>Agente Dahlgren</b><small>Un punto de entrada inteligente</small></button>');
    html=html.replace('<div class="avatar">DA</div>','<div class="profile-menu"><button class="avatar" data-profile-menu aria-expanded="false" aria-label="Abrir menú de presentación"><svg class="profile-avatar-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="4"></circle><path d="M4.5 20c.7-4 3.1-6 7.5-6s6.8 2 7.5 6"></path></svg></button><div class="profile-dropdown" hidden><span>PRESENTACIÓN</span><a href="mapa-transformacion.html">Mapa de transformación</a><a href="maqueta-original.html">Ver maqueta original</a></div></div>');
    return html;
  };
  document.addEventListener('click',e=>{let b=e.target.closest('[data-evo-toast]');if(b){e.preventDefault();toast(b.dataset.evoToast)} let a=e.target.closest('[data-evo-agent]');if(a){e.preventDefault();openFloatingChat()} let sync=e.target.closest('[data-onedrive-sync]');if(sync){e.preventDefault();openOneDriveSync()} let profile=e.target.closest('[data-profile-menu]');if(profile){let menu=profile.parentElement.querySelector('.profile-dropdown'),open=menu.hidden;document.querySelectorAll('.profile-dropdown').forEach(x=>x.hidden=true);menu.hidden=!open;profile.setAttribute('aria-expanded',String(open));}else if(!e.target.closest('.profile-menu'))document.querySelectorAll('.profile-dropdown').forEach(x=>x.hidden=true); });
  function openOneDriveSync(){document.querySelector('#onedrive-sync-modal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="onedrive-sync-modal"><div class="modal-box"><div class="eyebrow">OneDrive · demostración</div><h2>Sincronizar origen documental</h2><p class="muted">La futura integración detectará cambios en OneDrive y asociará cada archivo a su contexto. Esta acción no se conecta a ninguna cuenta.</p><div class="sync-modal-state"><b>Estado de conexión: pendiente de configuración</b>Requiere autorización Microsoft, selección del repositorio y definición de reglas de asociación.</div><div class="modal-actions"><button class="outline" data-onedrive-close>Cancelar</button><button class="primary" data-onedrive-start>Simular sincronización</button></div></div></div>`);let layer=document.querySelector('#onedrive-sync-modal');layer.addEventListener('click',event=>{if(event.target===layer||event.target.closest('[data-onedrive-close]'))layer.remove();if(event.target.closest('[data-onedrive-start]')){let button=event.target.closest('[data-onedrive-start]');button.textContent='Detectando cambios…';button.disabled=true;setTimeout(()=>{layer.querySelector('.modal-box').innerHTML=`<div class="eyebrow">Sincronización simulada</div><h2>3 documentos detectados</h2><div class="sync-modal-state"><b>DDJJ IVA, Acta de directorio y Papel de trabajo</b>Fueron asociados visualmente a Alto Paraná S.A.; los datos extraídos quedan pendientes de revisión profesional.</div><div class="modal-actions"><button class="primary" data-onedrive-close>Listo</button></div>`},700)}})}
  let chatOpen=false;
  const contextForChat=()=>{
    if(state.profile==='Cliente')return ['Portal Cliente · Grupo Battaglia','Mostrame mis últimas DDJJ.'];
    if(state.page.startsWith('entidad/')||state.page==='obligacion'||state.page==='novedad')return ['Alto Paraná S.A. · Impositivo · IVA agosto 2026','¿Qué vence esta semana para Alto Paraná S.A.?'];
    if(state.page.startsWith('grupo/'))return ['Grupo Battaglia · 3 entidades','¿Qué asuntos requieren intervención de un socio?'];
    if(state.page==='tareas')return ['Atención y tareas · Alto Paraná S.A.','Resumime la comunicación detectada y proponé el seguimiento.'];
    return ['Estudio · Dirección','¿Cómo vienen las cobranzas respecto del mes anterior?'];
  };
  const chatMarkup=()=>{let [context,suggestion]=contextForChat();return `<button class="floating-agent-button" aria-label="Abrir Agente Dahlgren" data-floating-chat><span>✦</span><b>Agente Dahlgren</b></button><aside class="floating-agent-panel ${chatOpen?'is-open':''}" aria-label="Chat con Agente Dahlgren"><header><div class="floating-agent-title"><span>✦</span><div><b>Agente Dahlgren</b><small>${context}</small></div></div><button aria-label="Cerrar chat" data-floating-close>×</button></header><div class="floating-messages"><div class="agent-message"><p>¿En qué te puedo ayudar?</p></div></div><div class="floating-suggestions"><button data-floating-suggest="${suggestion}">${suggestion}</button><button data-floating-suggest="Mostrame los documentos asociados.">Ver documentos</button></div><div class="floating-input"><input data-floating-input placeholder="Escribí una consulta…"><button data-floating-voice aria-label="Consulta por voz">⌁</button><button class="primary" data-floating-send>Enviar</button></div><footer><button data-go="comunicaciones" data-floating-full>Ampliar conversación ↗</button></footer></aside>`};
  function mountFloatingChat(){
    if(state.page==='login'){document.querySelector('.floating-agent-layer')?.remove();return}
    let layer=document.querySelector('.floating-agent-layer');
    if(!layer){layer=document.createElement('div');layer.className='floating-agent-layer';document.body.appendChild(layer)}
    layer.innerHTML=chatMarkup();
    layer.querySelector('[data-floating-chat]').onclick=openFloatingChat;
    layer.querySelector('[data-floating-close]').onclick=()=>{chatOpen=false;mountFloatingChat()};
    layer.querySelector('[data-floating-full]').onclick=()=>go('comunicaciones');
    layer.querySelectorAll('[data-floating-suggest]').forEach(b=>b.onclick=()=>{let input=layer.querySelector('[data-floating-input]');input.value=b.dataset.floatingSuggest;input.focus()});
    layer.querySelector('[data-floating-voice]').onclick=()=>toast('Entrada por voz disponible en modo demostración.');
    layer.querySelector('[data-floating-send]').onclick=()=>{
      let input=layer.querySelector('[data-floating-input]'),question=input.value.trim()||contextForChat()[1];
      layer.querySelector('.floating-messages').insertAdjacentHTML('beforeend',`<div class="user-message"><p>${question}</p></div><div class="agent-message"><p>Encontré información asociada a <strong>${contextForChat()[0]}</strong>. Hay un vencimiento y documentación para revisar.</p><button data-evo-toast="Detalle preparado con referencias y acciones sugeridas.">Ver detalle</button></div>`);
      input.value='';layer.querySelector('.floating-messages').scrollTop=layer.querySelector('.floating-messages').scrollHeight;
    };
  }
  function openFloatingChat(){chatOpen=true;mountFloatingChat();document.querySelector('.floating-agent-panel input')?.focus()}
  const appBeforeFloatingChat=app;
  app=function(){appBeforeFloatingChat();mountFloatingChat()};
  if(state.page!=='login')app();
})();
